/**
 * 全球国家列表
 * 包含国家名称（中英文）和国际区号
 */
export const countries = [
  { code: '93', name: 'Afghanistan', nameCn: '阿富汗' },
  { code: '355', name: 'Albania', nameCn: '阿尔巴尼亚' },
  { code: '213', name: 'Algeria', nameCn: '阿尔及利亚' },
  { code: '376', name: 'Andorra', nameCn: '安道尔' },
  { code: '244', name: 'Angola', nameCn: '安哥拉' },
  { code: '1264', name: 'Anguilla', nameCn: '安圭拉' },
  { code: '1268', name: 'Antigua and Barbuda', nameCn: '安提瓜和巴布达' },
  { code: '54', name: 'Argentina', nameCn: '阿根廷' },
  { code: '374', name: 'Armenia', nameCn: '亚美尼亚' },
  { code: '297', name: 'Aruba', nameCn: '阿鲁巴' },
  { code: '61', name: 'Australia', nameCn: '澳大利亚' },
  { code: '43', name: 'Austria', nameCn: '奥地利' },
  { code: '994', name: 'Azerbaijan', nameCn: '阿塞拜疆' },
  { code: '1242', name: 'Bahamas', nameCn: '巴哈马' },
  { code: '973', name: 'Bahrain', nameCn: '巴林' },
  { code: '880', name: 'Bangladesh', nameCn: '孟加拉国' },
  { code: '1246', name: 'Barbados', nameCn: '巴巴多斯' },
  { code: '375', name: 'Belarus', nameCn: '白俄罗斯' },
  { code: '32', name: 'Belgium', nameCn: '比利时' },
  { code: '501', name: 'Belize', nameCn: '伯利兹' },
  { code: '229', name: 'Benin', nameCn: '贝宁' },
  { code: '1441', name: 'Bermuda', nameCn: '百慕大' },
  { code: '975', name: 'Bhutan', nameCn: '不丹' },
  { code: '591', name: 'Bolivia', nameCn: '玻利维亚' },
  { code: '387', name: 'Bosnia and Herzegovina', nameCn: '波黑' },
  { code: '267', name: 'Botswana', nameCn: '博茨瓦纳' },
  { code: '55', name: 'Brazil', nameCn: '巴西' },
  { code: '673', name: 'Brunei', nameCn: '文莱' },
  { code: '359', name: 'Bulgaria', nameCn: '保加利亚' },
  { code: '226', name: 'Burkina Faso', nameCn: '布基纳法索' },
  { code: '257', name: 'Burundi', nameCn: '布隆迪' },
  { code: '855', name: 'Cambodia', nameCn: '柬埔寨' },
  { code: '237', name: 'Cameroon', nameCn: '喀麦隆' },
  { code: '1', name: 'Canada', nameCn: '加拿大' },
  { code: '238', name: 'Cape Verde', nameCn: '佛得角' },
  { code: '1345', name: 'Cayman Islands', nameCn: '开曼群岛' },
  { code: '236', name: 'Central African Republic', nameCn: '中非' },
  { code: '235', name: 'Chad', nameCn: '乍得' },
  { code: '56', name: 'Chile', nameCn: '智利' },
  { code: '86', name: 'China', nameCn: '中国' },
  { code: '57', name: 'Colombia', nameCn: '哥伦比亚' },
  { code: '269', name: 'Comoros', nameCn: '科摩罗' },
  { code: '242', name: 'Congo', nameCn: '刚果' },
  { code: '682', name: 'Cook Islands', nameCn: '库克群岛' },
  { code: '506', name: 'Costa Rica', nameCn: '哥斯达黎加' },
  { code: '385', name: 'Croatia', nameCn: '克罗地亚' },
  { code: '53', name: 'Cuba', nameCn: '古巴' },
  { code: '357', name: 'Cyprus', nameCn: '塞浦路斯' },
  { code: '420', name: 'Czech Republic', nameCn: '捷克' },
  { code: '45', name: 'Denmark', nameCn: '丹麦' },
  { code: '253', name: 'Djibouti', nameCn: '吉布提' },
  { code: '1767', name: 'Dominica', nameCn: '多米尼克' },
  { code: '1809', name: 'Dominican Republic', nameCn: '多米尼加' },
  { code: '593', name: 'Ecuador', nameCn: '厄瓜多尔' },
  { code: '20', name: 'Egypt', nameCn: '埃及' },
  { code: '503', name: 'El Salvador', nameCn: '萨尔瓦多' },
  { code: '240', name: 'Equatorial Guinea', nameCn: '赤道几内亚' },
  { code: '291', name: 'Eritrea', nameCn: '厄立特里亚' },
  { code: '372', name: 'Estonia', nameCn: '爱沙尼亚' },
  { code: '251', name: 'Ethiopia', nameCn: '埃塞俄比亚' },
  { code: '679', name: 'Fiji', nameCn: '斐济' },
  { code: '358', name: 'Finland', nameCn: '芬兰' },
  { code: '33', name: 'France', nameCn: '法国' },
  { code: '241', name: 'Gabon', nameCn: '加蓬' },
  { code: '220', name: 'Gambia', nameCn: '冈比亚' },
  { code: '995', name: 'Georgia', nameCn: '格鲁吉亚' },
  { code: '49', name: 'Germany', nameCn: '德国' },
  { code: '233', name: 'Ghana', nameCn: '加纳' },
  { code: '350', name: 'Gibraltar', nameCn: '直布罗陀' },
  { code: '30', name: 'Greece', nameCn: '希腊' },
  { code: '299', name: 'Greenland', nameCn: '格陵兰' },
  { code: '1473', name: 'Grenada', nameCn: '格林纳达' },
  { code: '1671', name: 'Guam', nameCn: '关岛' },
  { code: '502', name: 'Guatemala', nameCn: '危地马拉' },
  { code: '224', name: 'Guinea', nameCn: '几内亚' },
  { code: '245', name: 'Guinea-Bissau', nameCn: '几内亚比绍' },
  { code: '592', name: 'Guyana', nameCn: '圭亚那' },
  { code: '509', name: 'Haiti', nameCn: '海地' },
  { code: '504', name: 'Honduras', nameCn: '洪都拉斯' },
  { code: '852', name: 'Hong Kong', nameCn: '香港' },
  { code: '36', name: 'Hungary', nameCn: '匈牙利' },
  { code: '354', name: 'Iceland', nameCn: '冰岛' },
  { code: '91', name: 'India', nameCn: '印度' },
  { code: '62', name: 'Indonesia', nameCn: '印度尼西亚' },
  { code: '98', name: 'Iran', nameCn: '伊朗' },
  { code: '964', name: 'Iraq', nameCn: '伊拉克' },
  { code: '353', name: 'Ireland', nameCn: '爱尔兰' },
  { code: '972', name: 'Israel', nameCn: '以色列' },
  { code: '39', name: 'Italy', nameCn: '意大利' },
  { code: '1876', name: 'Jamaica', nameCn: '牙买加' },
  { code: '81', name: 'Japan', nameCn: '日本' },
  { code: '962', name: 'Jordan', nameCn: '约旦' },
  { code: '7', name: 'Kazakhstan', nameCn: '哈萨克斯坦' },
  { code: '254', name: 'Kenya', nameCn: '肯尼亚' },
  { code: '686', name: 'Kiribati', nameCn: '基里巴斯' },
  { code: '965', name: 'Kuwait', nameCn: '科威特' },
  { code: '996', name: 'Kyrgyzstan', nameCn: '吉尔吉斯斯坦' },
  { code: '856', name: 'Laos', nameCn: '老挝' },
  { code: '371', name: 'Latvia', nameCn: '拉脱维亚' },
  { code: '961', name: 'Lebanon', nameCn: '黎巴嫩' },
  { code: '266', name: 'Lesotho', nameCn: '莱索托' },
  { code: '231', name: 'Liberia', nameCn: '利比里亚' },
  { code: '218', name: 'Libya', nameCn: '利比亚' },
  { code: '423', name: 'Liechtenstein', nameCn: '列支敦士登' },
  { code: '370', name: 'Lithuania', nameCn: '立陶宛' },
  { code: '352', name: 'Luxembourg', nameCn: '卢森堡' },
  { code: '853', name: 'Macau', nameCn: '澳门' },
  { code: '389', name: 'Macedonia', nameCn: '马其顿' },
  { code: '261', name: 'Madagascar', nameCn: '马达加斯加' },
  { code: '265', name: 'Malawi', nameCn: '马拉维' },
  { code: '60', name: 'Malaysia', nameCn: '马来西亚' },
  { code: '960', name: 'Maldives', nameCn: '马尔代夫' },
  { code: '223', name: 'Mali', nameCn: '马里' },
  { code: '356', name: 'Malta', nameCn: '马耳他' },
  { code: '692', name: 'Marshall Islands', nameCn: '马绍尔群岛' },
  { code: '222', name: 'Mauritania', nameCn: '毛里塔尼亚' },
  { code: '230', name: 'Mauritius', nameCn: '毛里求斯' },
  { code: '52', name: 'Mexico', nameCn: '墨西哥' },
  { code: '691', name: 'Micronesia', nameCn: '密克罗尼西亚' },
  { code: '373', name: 'Moldova', nameCn: '摩尔多瓦' },
  { code: '377', name: 'Monaco', nameCn: '摩纳哥' },
  { code: '976', name: 'Mongolia', nameCn: '蒙古' },
  { code: '382', name: 'Montenegro', nameCn: '黑山' },
  { code: '1664', name: 'Montserrat', nameCn: '蒙特塞拉特' },
  { code: '212', name: 'Morocco', nameCn: '摩洛哥' },
  { code: '258', name: 'Mozambique', nameCn: '莫桑比克' },
  { code: '95', name: 'Myanmar', nameCn: '缅甸' },
  { code: '264', name: 'Namibia', nameCn: '纳米比亚' },
  { code: '674', name: 'Nauru', nameCn: '瑙鲁' },
  { code: '977', name: 'Nepal', nameCn: '尼泊尔' },
  { code: '31', name: 'Netherlands', nameCn: '荷兰' },
  { code: '64', name: 'New Zealand', nameCn: '新西兰' },
  { code: '505', name: 'Nicaragua', nameCn: '尼加拉瓜' },
  { code: '227', name: 'Niger', nameCn: '尼日尔' },
  { code: '234', name: 'Nigeria', nameCn: '尼日利亚' },
  { code: '850', name: 'North Korea', nameCn: '朝鲜' },
  { code: '47', name: 'Norway', nameCn: '挪威' },
  { code: '968', name: 'Oman', nameCn: '阿曼' },
  { code: '92', name: 'Pakistan', nameCn: '巴基斯坦' },
  { code: '680', name: 'Palau', nameCn: '帕劳' },
  { code: '970', name: 'Palestine', nameCn: '巴勒斯坦' },
  { code: '507', name: 'Panama', nameCn: '巴拿马' },
  { code: '675', name: 'Papua New Guinea', nameCn: '巴布亚新几内亚' },
  { code: '595', name: 'Paraguay', nameCn: '巴拉圭' },
  { code: '51', name: 'Peru', nameCn: '秘鲁' },
  { code: '63', name: 'Philippines', nameCn: '菲律宾' },
  { code: '48', name: 'Poland', nameCn: '波兰' },
  { code: '351', name: 'Portugal', nameCn: '葡萄牙' },
  { code: '1787', name: 'Puerto Rico', nameCn: '波多黎各' },
  { code: '974', name: 'Qatar', nameCn: '卡塔尔' },
  { code: '40', name: 'Romania', nameCn: '罗马尼亚' },
  { code: '7', name: 'Russia', nameCn: '俄罗斯' },
  { code: '250', name: 'Rwanda', nameCn: '卢旺达' },
  { code: '1869', name: 'Saint Kitts and Nevis', nameCn: '圣基茨和尼维斯' },
  { code: '1758', name: 'Saint Lucia', nameCn: '圣卢西亚' },
  { code: '685', name: 'Samoa', nameCn: '萨摩亚' },
  { code: '378', name: 'San Marino', nameCn: '圣马力诺' },
  { code: '966', name: 'Saudi Arabia', nameCn: '沙特阿拉伯' },
  { code: '221', name: 'Senegal', nameCn: '塞内加尔' },
  { code: '381', name: 'Serbia', nameCn: '塞尔维亚' },
  { code: '248', name: 'Seychelles', nameCn: '塞舌尔' },
  { code: '232', name: 'Sierra Leone', nameCn: '塞拉利昂' },
  { code: '65', name: 'Singapore', nameCn: '新加坡' },
  { code: '421', name: 'Slovakia', nameCn: '斯洛伐克' },
  { code: '386', name: 'Slovenia', nameCn: '斯洛文尼亚' },
  { code: '677', name: 'Solomon Islands', nameCn: '所罗门群岛' },
  { code: '252', name: 'Somalia', nameCn: '索马里' },
  { code: '27', name: 'South Africa', nameCn: '南非' },
  { code: '82', name: 'South Korea', nameCn: '韩国' },
  { code: '211', name: 'South Sudan', nameCn: '南苏丹' },
  { code: '34', name: 'Spain', nameCn: '西班牙' },
  { code: '94', name: 'Sri Lanka', nameCn: '斯里兰卡' },
  { code: '249', name: 'Sudan', nameCn: '苏丹' },
  { code: '597', name: 'Suriname', nameCn: '苏里南' },
  { code: '268', name: 'Swaziland', nameCn: '斯威士兰' },
  { code: '46', name: 'Sweden', nameCn: '瑞典' },
  { code: '41', name: 'Switzerland', nameCn: '瑞士' },
  { code: '963', name: 'Syria', nameCn: '叙利亚' },
  { code: '886', name: 'Taiwan', nameCn: '台湾' },
  { code: '992', name: 'Tajikistan', nameCn: '塔吉克斯坦' },
  { code: '255', name: 'Tanzania', nameCn: '坦桑尼亚' },
  { code: '66', name: 'Thailand', nameCn: '泰国' },
  { code: '670', name: 'Timor-Leste', nameCn: '东帝汶' },
  { code: '228', name: 'Togo', nameCn: '多哥' },
  { code: '676', name: 'Tonga', nameCn: '汤加' },
  { code: '1868', name: 'Trinidad and Tobago', nameCn: '特立尼达和多巴哥' },
  { code: '216', name: 'Tunisia', nameCn: '突尼斯' },
  { code: '90', name: 'Turkey', nameCn: '土耳其' },
  { code: '993', name: 'Turkmenistan', nameCn: '土库曼斯坦' },
  { code: '688', name: 'Tuvalu', nameCn: '图瓦卢' },
  { code: '256', name: 'Uganda', nameCn: '乌干达' },
  { code: '380', name: 'Ukraine', nameCn: '乌克兰' },
  { code: '971', name: 'United Arab Emirates', nameCn: '阿联酋' },
  { code: '44', name: 'United Kingdom', nameCn: '英国' },
  { code: '1', name: 'United States', nameCn: '美国' },
  { code: '598', name: 'Uruguay', nameCn: '乌拉圭' },
  { code: '998', name: 'Uzbekistan', nameCn: '乌兹别克斯坦' },
  { code: '678', name: 'Vanuatu', nameCn: '瓦努阿图' },
  { code: '58', name: 'Venezuela', nameCn: '委内瑞拉' },
  { code: '84', name: 'Vietnam', nameCn: '越南' },
  { code: '1340', name: 'Virgin Islands US', nameCn: '美属维尔京群岛' },
  { code: '967', name: 'Yemen', nameCn: '也门' },
  { code: '260', name: 'Zambia', nameCn: '赞比亚' },
  { code: '263', name: 'Zimbabwe', nameCn: '津巴布韦' }
]

export default countries
